global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "ubuntu-servers"
    static_configs:
      - targets:
          - 192.168.88.29:9100
          - 192.168.88.30:9100

  - job_name: "windows-servers"
    static_configs:
      - targets:
          - 192.168.88.25:9182