---
- name: Install Packages
  hosts: all
  become: yes
  tasks:
    - name: Install Specified Packages
      package:
        name: "{{ item }}"
        state: present
      loop: "{{ packages }}"

# ansible-playbook playbooks/install_packages.yml --extra-vars "packages=['nginx', 'vim']"