---
- name: "Install Prometheus on Server"
  hosts: all
  gather_facts: false
  become: true
  become_user: root
  tasks:
    - name: "Install Docker and Docker Compose"
      ansible.builtin.script: ../provision/compose.install.sh
      register: result

    - name: "Show Output of Docker Install Process"
      ansible.builtin.debug: var=result.stdout_lines

    - name: "Install Docker containers: Prometheus & Grafana"
      command: docker compose -f docker-compose.yml up -d
      args:
        chdir: /provision/prometheus-grafana-docker